name: Plugin Linter
description: A plugin to lint your Buildkite plugins
author: "https://github.com/buildkite"
requirements:
  - docker
configuration:
  properties:
    id:
      type: string
    image-version:
      type: string
    readme:
      type: string
    skip-invalid:
      type: boolean
  required:
    - id
  additionalProperties: false