name: plugin-linter
description: A plugin to lint your Buildkite plugins
author: "https://github.com/buildkite"
requirements:
  - docker
configuration:
  properties:
    name:
      type: string
    readme:
      type: string
  required:
    - name
  additionalProperties: false